version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    # ports:
    #   - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]



  gsm8k-eval:
    build: .
    image: rag-eval
    depends_on:
      - ollama
    restart: "no"
    container_name: RAG-eval-ver2
    environment:
      - OLLAMA_API=http://ollama:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WANDB_API_KEY=${WANDB_API_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
    # command: python gsm8k_eval.py
    command: tail -f /dev/null
    volumes:
      - .:/app
      - ./hf_cache:/root/.cache/huggingface  # ← 追加
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    runtime: nvidia           # ← これも有効にするとより確実

volumes:
  ollama_data:
